# Generated by Django 3.1.1 on 2020-09-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zain_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='body',
            field=models.TextField(),
        ),
    ]
